### ISSUE TITLE
Can sparkline be inserted to a shiny datatable?

### ISSUE THREAD

**Issue by aharach** [Bart6114/sparklines#1]
Hi Bart, thanks very much for sharing this really useful R package.  

And one question is to whether `sparkline` function providing any html output, so that spark plots can be shown in a column in the Shiny datatable?

Currently, I can only find `sparklines` package providing standard output from `sparkline` function.

**Comment by bart6114** [comment]
Please refer to https://github.com/htmlwidgets/sparkline for the correct version of the library. Consider this repo as archived.
